# Generated by Django 4.0.2 on 2022-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_type', models.CharField(max_length=50)),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_title_eng', models.CharField(max_length=100)),
                ('movie_like', models.CharField(max_length=100)),
                ('movie_score', models.CharField(max_length=100)),
                ('movie_rank', models.CharField(max_length=100)),
                ('movie_rate', models.CharField(max_length=100)),
                ('movie_audience', models.CharField(max_length=100)),
                ('movie_age', models.CharField(max_length=100)),
                ('movie_summary', models.TextField(max_length=1000)),
                ('movie_type2', models.CharField(max_length=50)),
                ('movie_line1', models.CharField(max_length=100)),
                ('movie_line2', models.CharField(max_length=100)),
                ('movie_line3', models.CharField(max_length=100)),
                ('movie_line4', models.CharField(max_length=100)),
                ('movie_line5', models.CharField(max_length=100)),
                ('movie_actor', models.CharField(max_length=500)),
                ('movie_url_bg_poster', models.CharField(max_length=500)),
                ('movie_url_poster', models.CharField(max_length=500)),
                ('movie_graph01', models.CharField(max_length=500)),
                ('movie_graph03', models.CharField(max_length=500)),
                ('movie_graph04', models.CharField(max_length=500)),
            ],
        ),
    ]
